test/web: Increase default wait() timeout to 15 seconds.
Make the wait() function time out after 15 seconds rather
than 10. This hopefully prevents a flaky failure that I just
saw on Cloud Build:

=== RUN   TestPlaybackButtons
    page.go:800: Bad song at web_test.go:610: timed out: songs don't match
        Want: ["artist" "track2" "album" playing]
        Got:  ["artist" "track1" "album" unended playing filename="10s.mp3" rating="" time="[ 0:08 / 0:10 ]" title="Unrated\n(Alt+R or Alt+T to edit)"]
--- FAIL: TestPlaybackButtons (12.25s)

This test seemed reasonable when I wrote it, but 5be70da5
switched it to use a 10-second song rather than 5-second, so
we need to wait more than 10 seconds to play through the
song now.